name: 'Force Delete SAP BTP Subaccount'
description: 'Action for force deleting SAP BTP subaccount'

inputs:
  btp_subaccount_id:
    description: 'btp subaccount id'
    required: true
  btp_backend_url:
    description: 'btp backend url'
    required: true
  btp_user:
    description: 'btp user'
    required: true
  btp_password:
    description: 'btp password'
    required: true
  btp_global_account:
    description: 'btp global account'
    required: true
  btp_idp_tenant:
    description: 'btp idp tenant'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-btp
    - name: Force delete btp resources
      shell: bash
      run: |
        btp login --url "${{ inputs.btp_backend_url }}" --user "${{ inputs.btp_user }}" --password "${{ inputs.btp_password }}" --idp "${{ inputs.btp_idp_tenant }}"  --subdomain "${{ inputs.btp_global_account }}"
        echo "Deleting ${{ inputs.btp_global_account }}/${{ inputs.btp_subaccount_id }}".
        btp delete accounts/subaccount "${{ inputs.btp_subaccount_id }}" --global-account "${{ inputs.btp_global_account }}" --force-delete true --confirm true
        echo "Deletion request for subaccount ${{ inputs.btp_subaccount_id }} sent."
        
